---
- name: Installer nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copier la configuration Nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/wordpress.conf
  notify: Restart nginx

- name: Activer le site Wordpress
  file:
    src: /etc/nginx/sites-available/wordpress.conf
    dest: /etc/nginx/sites-enabled/wordpress.conf
    state: link
    force: yes

- name: Supprimer le site par défaut
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
