---

- name: Reload haproxy
  ansible.builtin.service:
    name: "{{ item }}"
    state: reloaded
  loop:
    - haproxy

- name: Restart haproxy
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - haproxy
