---

- hosts: dbservers

  pre_tasks:
    - name: Updating APT cache
      ansible.builtin.apt:
        update_cache: yes

  tasks:
    - name: install MariaDB server
      ansible.builtin.apt:
        name: mariadb-server
        update_cache: yes
        state: present

  handlers:
    - name: restart_mariadb
      ansible.builtin.service:
        name: mariadb
        state: restarted