---

- hosts: webservers

  roles:
    - role: motd

  pre_tasks:
    - ansible.builtin.import_tasks: common.yml

  tasks:
    - name: Install Nginx web server
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: Nginx status configuration file
      ansible.builtin.copy:
        src: nginx/status.conf
        dest: /etc/nginx/conf.d/status.conf
      notify:
        - restart_nginx
      tags:
        - nginx
        - configuration

    - name: Install PHP-FPM service
      ansible.builtin.apt:
        name: php-fpm
        state: present
      when: php.enabled

    - name: PHP-FPM > Configuration
      ansible.builtin.template:
        src: "php/app.ini.j2"
        dest: "/etc/php/8.2/fpm/app.ini"
      notify: restart_php-fpm
      when: php.enabled

  handlers:
    - ansible.builtin.import_tasks: handlers.yml