---

- name: Restart redis
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - redis-server

- name: Restart redis-sentinel
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - redis-sentinel
