---
- name: Installer dépendance Python pour Ansible
  apt:
    name: python3-mysqldb
    state: present

- name: Installer MariaDB
  apt:
    name: mariadb-server
    state: present
    update_cache: yes

- name: S'assurer que MariaDB est actif
  service:
    name: mysql
    state: started
    enabled: yes

- name: Installer le connecteur PyMySQL
  apt:
    name: python3-pymysql
    state: present

- name: Créer la base de données
  community.mysql.mysql_db:
    name: "{{ mysql.db_name }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Créer l'utilisateur MySQL
  community.mysql.mysql_user:
    name: "{{ mysql.user }}"
    password: "{{ mysql.password }}"
    priv: "{{ mysql.db_name }}.*:ALL"
    host: "localhost"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
    column_case_sensitive: false
