all:
  hosts:
    server-01:
      ansible_host: 192.168.95.129
      ansible_user: ansible
      ansible_python_interpreter: /usr/bin/python3
    server-02:
      ansible_host: 192.168.95.130
      ansible_user: ansible
      ansible_python_interpreter: /usr/bin/python3
  children:
    webservers:
      hosts:
        server-01: {}
        server-02: {}
    dbservers:
      hosts:
        server-01: {}
        server-02: {}
    staging:
      hosts:
        server-02: {}
    production:
      hosts:
        server-01: {}
