all:
  hosts:
    server-01:
      ansible_host: 192.168.95.129
      ansible_user: ansible
    server-02:
      ansible_host: 192.168.95.130
      ansible_user: ansible
  children:
    webservers:
      hosts:
        server-01: ~
        server-02: ~
    dbservers:
      hosts:
        server-01: ~
        server-02: ~
    staging:
      hosts:
        server-02: ~
    production:
      hosts:
        server-01: ~
      

