---

- name: Restart nginx
  ansible.builtin.command:
    cmd: nginx -t
  changed_when: true
  notify:
    - Do restart nginx

- name: Do restart nginx
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  loop:
    - nginx
