---
- name: Installer PHP et extensions nécessaires
  apt:
    name:
      - php
      - php{{ php_version }}
      - php{{ php_version }}-fpm
      - php{{ php_version }}-mysql
      - php{{ php_version }}-cli
    state: present
    update_cache: yes

- name: Installer le connecteur PyMySQL
  apt:
    name: python3-pymysql
    state: present

- name: S'assurer que PHP-FPM est lancé
  service:
    name: php{{ php_version }}-fpm
    state: started
    enabled: yes
