---

- name: Restart prometheus
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: true
  loop:
    - "{{ manala_prometheus_service }}"

#################
# Node Exporter #
#################

- name: Restart prometheus node exporter
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: true
  loop:
    - "{{ manala_prometheus_node_exporter_service }}"

##################
# Nginx Exporter #
##################

- name: Restart prometheus nginx exporter
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: true
  loop:
    - "{{ manala_prometheus_nginx_exporter_service }}"

####################
# Php Fpm Exporter #
####################

- name: Restart prometheus php fpm exporter
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: true
  loop:
    - "{{ manala_prometheus_php_fpm_exporter_service }}"
